export const CHANGE_TAB_TL = 'CHANGE_TAB_TL';
export const CHANGE_TAB_LL = 'CHANGE_TAB_LL';
export const SELECT_NEW_PRODUCT = 'SELECT_NEW_PRODUCT';
export const SELECT_NEW_PRODUCT_COLOR = 'SELECT_NEW_PRODUCT_COLOR';

export const UPLOAD_IMAGE_INIT = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_FAILURE';

export const CHANGE_ORDER_QUANTITY = 'CHANGE_ORDER_QUANTITY';

export const CLICK_ADDTOCART = 'CLICK_ADDTOCART';
export const CLICK_ADDTOCART_SUCCESS = 'CLICK_ADDTOCART_SUCCESS';
export const CLICK_ADDTOCART_ERROR = 'CLICK_ADDTOCART_ERROR';
