export const CHANGE_TAB_TL = 'CHANGE_TAB_TL';
export const CHANGE_TAB_LL = 'CHANGE_TAB_LL';
export const SELECT_NEW_PRODUCT = 'SELECT_NEW_PRODUCT';
export const SELECT_NEW_PRODUCT_COLOR = 'SELECT_NEW_PRODUCT_COLOR';
